# Generated by Django 4.2.21 on 2025-06-05 00:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
            ],
            options={
                'ordering': ['start', 'end'],
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pattern', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nih_db', models.TextField()),
                ('nih_id', models.TextField()),
                ('type', models.TextField()),
                ('seqtype', models.TextField()),
                ('accver', models.TextField()),
                ('taxid', models.TextField()),
                ('orgname', models.TextField()),
                ('defline', models.TextField()),
                ('length', models.IntegerField()),
                ('sequence', models.TextField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='sequence',
            constraint=models.UniqueConstraint(fields=('nih_db', 'nih_id', 'type'), name='unique_sequence_data'),
        ),
        migrations.AddField(
            model_name='searchterm',
            name='matches',
            field=models.ManyToManyField(related_name='search_terms', to='api.match'),
        ),
        migrations.AddField(
            model_name='searchterm',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sequence'),
        ),
        migrations.AddField(
            model_name='search',
            name='search_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.searchterm'),
        ),
        migrations.AddField(
            model_name='match',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sequence'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['start', 'end', 'sequence'], name='api_match_start_c07002_idx'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('start', 'end'), name='unique_match_range'),
        ),
    ]
