services:
  redis:
    image: redis:7
    command: [ "redis-server", "--maxmemory-policy", "allkeys-lru" ]

  backend:
    build:
      context: backend
    expose:
      - "8000"
    volumes:
#      - ./backend/db.sqlite3:/app/db.sqlite3
#      - ./backend:/app
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - redis
    environment:
      - DJANGO_ENV=${DJANGO_ENV}

# build only
  frontend:
    build:
      context: frontend
    volumes:
      - frontend-build:/app/dist

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend-build:/var/www/frontend:ro
      - static_volume:/var/www/static
      - media_volume:/var/www/media
    depends_on:
      - backend

volumes:
  frontend-build:
  static_volume:
  media_volume:
