# Generated by Django 4.2.21 on 2025-06-05 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='search_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search', to='api.searchterm'),
        ),
    ]
