# Generated by Django 4.2.21 on 2025-06-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='searchterm',
            name='pattern',
            field=models.TextField(unique=True),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['start', 'end', 'sequence'], name='api_match_start_c07002_idx'),
        ),
    ]
